version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
      - ./config.yml:/app/config.yml
    container_name: weather_service
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=weather_service
  database:
    image: postgres:13-alpine
    container_name: postgres-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: weather_service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: