version: '3.8'

services:
  db:
    image: postgres:13
    container_name: weather_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: weather_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - weather_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather_service
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: weather_db
    networks:
      - weather_network

volumes:
  db_data:

networks:
  weather_network:
